import Head from 'next/head'

export default function Home() {
  return (
    <div className="Home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <center>
        <h1>Insert Waivez Content Here</h1>
      </center>

    </div>
  )
}
